### ISSUE TITLE
Invitation email has really small letters in some email clients

### ISSUE THREAD

**Issue by mconf-daileon** [mconf/mconf-web#814] opened 2016-05-08 16:49 UTC
---

Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Redmine Issue: 1865, http://dev.mconf.org/redmine/issues/1865

---

We've seen that for users using Outlook Web App, the invitation email to join a conference is being shown with letter really, really small, something visible similar to a 1px or 2px font-size.
The same email, however, looks good in most of the other email clients.

Might be just a matter of setting the font-size properly in the css so that it works with different browsers/email clients.

**Comment by mconf-daileon** [comment] 2016-05-08 16:49
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2015-12-17T19:04:47Z

---

This is likely something that happens only on Outlook Web App or other old mail clients. Maybe the version of Outlook Web App where this error was seen doesn't support css properly.

See more at: https://www.campaignmonitor.com/blog/email-marketing/2011/09/email-rendering-issues-and-fixes-for-outlook-web-app-owa/

**Comment by mconf-daileon** [comment] 2016-05-08 16:49
---

Original Redmine Comment
Author Name: **Leonardo Daronco** (Leonardo Daronco)
Original Date: 2016-01-04T15:53:15Z

---

I'm attaching a print of how it looks in Zimbra. The letters are even smaller in Outlook Web App.

**Comment by RafaFP** [comment] 2016-09-09 18:19
I have tested this issue in several scenarios, icluding some of the described above.

The emails sent to Gmail, Outlook (seen on webapp) and Zoho have not been received with the kind of problems reported here. The character font size was regular in both clients, which were reported to show the issue. 

This is a test e-mail sent to Outlook and checked on the browser version:
![image](https://cloud.githubusercontent.com/assets/1259141/18397759/ff11f9ba-769f-11e6-8126-d092cc433e16.png)

This is a test e-mail sent to Zoho, and also checked on browser version of the client:
![image](https://cloud.githubusercontent.com/assets/1259141/18397827/41001c8a-76a0-11e6-8504-4d8add81495c.png)

I suggest this issue to be closed if there are no longer any reports of this behavior.

**Comment by daronco** [comment] 2016-09-12 13:57
We'll close this since we can't find a way to reproduce it. It might happen only in very old email clients.

**Closed by daronco** 2016-09-12 13:57 UTC
Labels: prio:medium, status:feedback, type:bug
